---
apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    app: nginx
spec:
  rules:
  - host: web.app
    http:
      paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 8000
